### ISSUE TITLE
Demo compile can't find tjpgd.h

### ISSUE THREAD

**Issue by wriede** [teastainGit/LilyGO-T-display-S3-setup-and-examples#15]
Why do I get this error even though I have the Tjpg_Decode library installed?

~/Arduino/libraries/LilyGo-EPD47/src/libjpeg/libjpeg.c:17:10: fatal error: esp32/rom/tjpgd.h: No such file or directory
   17 | #include "esp32/rom/tjpgd.h"

![Image](https://github.com/user-attachments/assets/3d45e036-63fe-467e-9ffa-d3ca71444829)

**Comment by teastainGit** [comment]
This file is intended for the e-paper model with a different screen:
https://lilygo.cc/products/t5-4-7-inch-e-paper-v2-3
Maybe this is the cause.

**Comment by wriede** [comment]
So it may well be that the demo isn't going to work on my 2.4 but the program should still compile, shouldn't it?

**Comment by teastainGit** [comment]
What do you hope to achieve with this project?

**Comment by wriede** [comment]
I figured I'd use the Demo to iron out the environment and process to compile and load something on the Lilygo T5 and then move on to use it to display (slowly changing) info from Home Assistant and if I can get Touch to work be able to press to select the category displayed.

**Comment by teastainGit** [comment]
What esp32 by espressif board definition (Boards Manager)  are you using?
Many LilyGO products will not work with ver 3.x.x.
Try ver 2.0.14.
